server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1
    username: root
    password: leutoi309
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: thanhpthe163909@fpt.edu.vn
    password: iuka tccz excq flbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your_very_secure_secret_key_that_is_at_least_32_characters_long

